/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Address;

/**
 *
 * @author kalyanijohare
 */
public class AddressViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddressViewJPanel
     */
    
    Address address;
    public AddressViewJPanel(Address address) {
        initComponents();
        this.address = address;
        displayaddress();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStreetAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        lblAddressTitle = new javax.swing.JLabel();
        lblStreetAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        txtStreetAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtStreetAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressActionPerformed(evt);
            }
        });

        txtCity.setBackground(new java.awt.Color(204, 204, 204));
        txtCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtState.setBackground(new java.awt.Color(204, 204, 204));
        txtState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtZipCode.setBackground(new java.awt.Color(204, 204, 204));
        txtZipCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        lblAddressTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblAddressTitle.setText("Address Information");

        lblStreetAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblStreetAddress.setText("Street Address:");

        lblCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblState.setText("State:");

        lblZipCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblZipCode.setText("Zip Code:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblAddressTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCity)
                                    .addComponent(lblStreetAddress)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblZipCode)
                                    .addComponent(lblState))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState)
                            .addComponent(txtCity)
                            .addComponent(txtStreetAddress))))
                .addContainerGap(543, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblAddressTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipCode))
                .addContainerGap(501, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed
    
    private void displayaddress() {
        txtStreetAddress.setText(address.getStreetAddress());
        txtCity.setText(address.getCity());
        txtState.setText(address.getState());
        txtZipCode.setText(address.getZipCode());
        
        txtStreetAddress.setEditable(false);
        txtCity.setEditable(false);
        txtState.setEditable(false);
        txtZipCode.setEditable(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddressTitle;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

   }
