/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.BankDetails;

/**
 *
 * @author kalyanijohare
 */
public class BankDetailsCreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankDetailsJPanel
     */
    BankDetails bankdetails;
    public BankDetailsCreateJPanel(BankDetails bankdetails) {
        initComponents();
        this.bankdetails =  bankdetails;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAccountBalance_S = new javax.swing.JTextField();
        txtAccountType_S = new javax.swing.JTextField();
        lblSavingsAccTtile = new javax.swing.JLabel();
        lblBankName_S = new javax.swing.JLabel();
        lblRoutingNumber_S = new javax.swing.JLabel();
        lblAccountNumber_S = new javax.swing.JLabel();
        lblAccountBalance_S = new javax.swing.JLabel();
        lblAccountType_S = new javax.swing.JLabel();
        txtBankName_S = new javax.swing.JTextField();
        txtRoutingNumber_S = new javax.swing.JTextField();
        txtAccountNumber_S = new javax.swing.JTextField();
        btnSaveSavingsInformation = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        txtAccountBalance_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountBalance_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAccountType_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountType_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblSavingsAccTtile.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblSavingsAccTtile.setText("Savings Account Information");

        lblBankName_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBankName_S.setText("Bank Name:");

        lblRoutingNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRoutingNumber_S.setText("Bank Routing Number:");

        lblAccountNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountNumber_S.setText("Bank Account Number:");

        lblAccountBalance_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountBalance_S.setText("Account Balance:");

        lblAccountType_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountType_S.setText("Account Type:");

        txtBankName_S.setBackground(new java.awt.Color(204, 204, 204));
        txtBankName_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtRoutingNumber_S.setBackground(new java.awt.Color(204, 204, 204));
        txtRoutingNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAccountNumber_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnSaveSavingsInformation.setBackground(new java.awt.Color(0, 102, 102));
        btnSaveSavingsInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSaveSavingsInformation.setText("Save");
        btnSaveSavingsInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSavingsInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAccountType_S)
                            .addComponent(lblBankName_S)
                            .addComponent(lblRoutingNumber_S)
                            .addComponent(lblAccountNumber_S)
                            .addComponent(lblAccountBalance_S))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRoutingNumber_S)
                            .addComponent(txtBankName_S)
                            .addComponent(txtAccountNumber_S)
                            .addComponent(txtAccountBalance_S)
                            .addComponent(txtAccountType_S, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblSavingsAccTtile))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnSaveSavingsInformation)))
                .addContainerGap(652, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblSavingsAccTtile)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName_S)
                    .addComponent(txtBankName_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoutingNumber_S)
                    .addComponent(txtRoutingNumber_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber_S)
                    .addComponent(txtAccountNumber_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountBalance_S, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountBalance_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType_S)
                    .addComponent(txtAccountType_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveSavingsInformation)
                .addContainerGap(413, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveSavingsInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSavingsInformationActionPerformed
        // TODO add your handling code here:
        bankdetails.setBankName(txtBankName_S.getText());
        bankdetails.setBankRoutingNumber(txtRoutingNumber_S.getText());
        bankdetails.setBankAccountNumber(txtRoutingNumber_S.getText());
        bankdetails.setAccountBalance(txtAccountBalance_S.getText());
        bankdetails.setAccountType(txtAccountType_S.getText());
        
        JOptionPane.showMessageDialog(this, "Savings Account Information Saved Successfully");
    }//GEN-LAST:event_btnSaveSavingsInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveSavingsInformation;
    private javax.swing.JLabel lblAccountBalance_S;
    private javax.swing.JLabel lblAccountNumber_S;
    private javax.swing.JLabel lblAccountType_S;
    private javax.swing.JLabel lblBankName_S;
    private javax.swing.JLabel lblRoutingNumber_S;
    private javax.swing.JLabel lblSavingsAccTtile;
    private javax.swing.JTextField txtAccountBalance_S;
    private javax.swing.JTextField txtAccountNumber_S;
    private javax.swing.JTextField txtAccountType_S;
    private javax.swing.JTextField txtBankName_S;
    private javax.swing.JTextField txtRoutingNumber_S;
    // End of variables declaration//GEN-END:variables
}
