/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.BankDetails;

/**
 *
 * @author kalyanijohare
 */
public class BankDetailsViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankDetailsViewJPanel
     */
    BankDetails bankdetails;
    public BankDetailsViewJPanel(BankDetails bankdetails) {
        initComponents();
        this.bankdetails = bankdetails;
        displayBankDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSavingsAccTtile = new javax.swing.JLabel();
        lblBankName_S = new javax.swing.JLabel();
        lblRoutingNumber_S = new javax.swing.JLabel();
        lblAccountNumber_S = new javax.swing.JLabel();
        lblAccountBalance_S = new javax.swing.JLabel();
        lblAccountType_S = new javax.swing.JLabel();
        txtBankName_S = new javax.swing.JTextField();
        txtRoutingNumber_S = new javax.swing.JTextField();
        txtAccountNumber_S = new javax.swing.JTextField();
        txtAccountBalance_S = new javax.swing.JTextField();
        txtAccountType_S = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 102));

        lblSavingsAccTtile.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblSavingsAccTtile.setText("Savings Account Information");

        lblBankName_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBankName_S.setText("Bank Name:");

        lblRoutingNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRoutingNumber_S.setText("Bank Routing Number:");

        lblAccountNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountNumber_S.setText("Bank Account Number:");

        lblAccountBalance_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountBalance_S.setText("Account Balance:");

        lblAccountType_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountType_S.setText("Account Type:");

        txtBankName_S.setBackground(new java.awt.Color(204, 204, 204));
        txtBankName_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtRoutingNumber_S.setBackground(new java.awt.Color(204, 204, 204));
        txtRoutingNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAccountNumber_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAccountBalance_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountBalance_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAccountType_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountType_S.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAccountType_S)
                            .addComponent(lblBankName_S)
                            .addComponent(lblRoutingNumber_S)
                            .addComponent(lblAccountNumber_S)
                            .addComponent(lblAccountBalance_S))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRoutingNumber_S)
                            .addComponent(txtBankName_S)
                            .addComponent(txtAccountNumber_S)
                            .addComponent(txtAccountBalance_S)
                            .addComponent(txtAccountType_S, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblSavingsAccTtile)))
                .addContainerGap(671, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblSavingsAccTtile, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName_S)
                    .addComponent(txtBankName_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoutingNumber_S)
                    .addComponent(txtRoutingNumber_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber_S)
                    .addComponent(txtAccountNumber_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountBalance_S, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountBalance_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType_S)
                    .addComponent(txtAccountType_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(470, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccountBalance_S;
    private javax.swing.JLabel lblAccountNumber_S;
    private javax.swing.JLabel lblAccountType_S;
    private javax.swing.JLabel lblBankName_S;
    private javax.swing.JLabel lblRoutingNumber_S;
    private javax.swing.JLabel lblSavingsAccTtile;
    private javax.swing.JTextField txtAccountBalance_S;
    private javax.swing.JTextField txtAccountNumber_S;
    private javax.swing.JTextField txtAccountType_S;
    private javax.swing.JTextField txtBankName_S;
    private javax.swing.JTextField txtRoutingNumber_S;
    // End of variables declaration//GEN-END:variables

    private void displayBankDetails() {
         txtBankName_S.setText(bankdetails.getBankName());
         txtRoutingNumber_S.setText(bankdetails.getBankRoutingNumber());
         txtAccountNumber_S.setText(bankdetails.getBankAccountNumber());
         txtAccountBalance_S.setText(bankdetails.getAccountBalance());
         txtAccountType_S.setText(bankdetails.getAccountType());
         
         txtBankName_S.setEditable(false);
         txtRoutingNumber_S.setEditable(false);
         txtAccountNumber_S.setEditable(false);
         txtAccountBalance_S.setEditable(false);
         txtAccountType_S.setEditable(false);
    }
}
