/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.BankDetails_CheckingAcc;

/**
 *
 * @author kalyanijohare
 */
public class CheckingAccCreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckingAccountDetails
     */
    BankDetails_CheckingAcc checkingAccount;
    public CheckingAccCreateJPanel(BankDetails_CheckingAcc checkingAccount) {
        initComponents();
        this.checkingAccount = checkingAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRoutingNumber_C = new javax.swing.JTextField();
        txtAccountNumber_C = new javax.swing.JTextField();
        txtAccountBalance_C = new javax.swing.JTextField();
        btnSaveCheckingsInformation = new javax.swing.JButton();
        txtAccountType_C = new javax.swing.JTextField();
        lblCheckingAccTtile = new javax.swing.JLabel();
        lblBankName_C = new javax.swing.JLabel();
        lblRoutingNumber_C = new javax.swing.JLabel();
        lblAccountNumber_C = new javax.swing.JLabel();
        lblAccountBalance_C = new javax.swing.JLabel();
        lblAccountType_C = new javax.swing.JLabel();
        txtBankName_C = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 102));

        txtRoutingNumber_C.setBackground(new java.awt.Color(204, 204, 204));
        txtRoutingNumber_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAccountNumber_C.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountNumber_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAccountBalance_C.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountBalance_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnSaveCheckingsInformation.setBackground(new java.awt.Color(0, 102, 102));
        btnSaveCheckingsInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSaveCheckingsInformation.setText("Save");
        btnSaveCheckingsInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCheckingsInformationActionPerformed(evt);
            }
        });

        txtAccountType_C.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountType_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblCheckingAccTtile.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblCheckingAccTtile.setText("Checking Account Information");

        lblBankName_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBankName_C.setText("Bank Name:");

        lblRoutingNumber_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRoutingNumber_C.setText("Bank Routing Number:");

        lblAccountNumber_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountNumber_C.setText("Bank Account Number:");

        lblAccountBalance_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountBalance_C.setText("Account Balance:");

        lblAccountType_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAccountType_C.setText("Account Type:");

        txtBankName_C.setBackground(new java.awt.Color(204, 204, 204));
        txtBankName_C.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnSaveCheckingsInformation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCheckingAccTtile)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAccountType_C)
                                    .addComponent(lblBankName_C)
                                    .addComponent(lblRoutingNumber_C)
                                    .addComponent(lblAccountNumber_C)
                                    .addComponent(lblAccountBalance_C))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRoutingNumber_C)
                                    .addComponent(txtBankName_C)
                                    .addComponent(txtAccountNumber_C)
                                    .addComponent(txtAccountBalance_C)
                                    .addComponent(txtAccountType_C, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(672, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblCheckingAccTtile)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName_C)
                    .addComponent(txtBankName_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoutingNumber_C)
                    .addComponent(txtRoutingNumber_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber_C)
                    .addComponent(txtAccountNumber_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountBalance_C, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountBalance_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType_C)
                    .addComponent(txtAccountType_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveCheckingsInformation)
                .addContainerGap(411, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCheckingsInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCheckingsInformationActionPerformed
        // TODO add your handling code here:
        checkingAccount.setBankName_C(txtBankName_C.getText());
        checkingAccount.setBankRoutingNumber_C(txtRoutingNumber_C.getText());
        checkingAccount.setBankAccountNumber_C(txtAccountNumber_C.getText());
        checkingAccount.setAccountBalance_C(txtAccountBalance_C.getText());
        checkingAccount.setAccountType_C(txtAccountType_C.getText());

        JOptionPane.showMessageDialog(this, "Checking Account Information Saved Successfully");
    }//GEN-LAST:event_btnSaveCheckingsInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCheckingsInformation;
    private javax.swing.JLabel lblAccountBalance_C;
    private javax.swing.JLabel lblAccountNumber_C;
    private javax.swing.JLabel lblAccountType_C;
    private javax.swing.JLabel lblBankName_C;
    private javax.swing.JLabel lblCheckingAccTtile;
    private javax.swing.JLabel lblRoutingNumber_C;
    private javax.swing.JTextField txtAccountBalance_C;
    private javax.swing.JTextField txtAccountNumber_C;
    private javax.swing.JTextField txtAccountType_C;
    private javax.swing.JTextField txtBankName_C;
    private javax.swing.JTextField txtRoutingNumber_C;
    // End of variables declaration//GEN-END:variables
}
