/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Address;
import model.BankDetails;
import model.BankDetails_CheckingAcc;
import model.LicenseInformation;
import model.MedicalRecord;
import model.Person;

/**
 *
 * @author kalyanijohare
 */
public class FinalViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinalViewJPanel
     */
    Person person;
    Address address;
    BankDetails bankdetails;
    BankDetails_CheckingAcc checkingAccount;
    LicenseInformation licenseInformation;
    MedicalRecord medicalRecord;
    public FinalViewJPanel(Person person, Address address,BankDetails bankdetails,BankDetails_CheckingAcc checkingAccount,LicenseInformation licenseInformation,MedicalRecord medicalRecord ) {
        initComponents();
        this.person = person;
        this.address = address;
        this.bankdetails = bankdetails;
        this.checkingAccount = checkingAccount;
        this.licenseInformation = licenseInformation;
        this.medicalRecord = medicalRecord;
        
        displayperson();
        displayaddress();
        displayBankDetails();
        displayCheckingAccount();
        displayLicenseInformation();
        displayMedicalRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblDateOfBirth = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblFinalPersonTitle = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        lblStreetAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lblFinalAddressTitle = new javax.swing.JLabel();
        txtAccountBalance_S = new javax.swing.JTextField();
        txtAccountType_S = new javax.swing.JTextField();
        lblBankName_S = new javax.swing.JLabel();
        lblRoutingNumber_S = new javax.swing.JLabel();
        lblAccountNumber_S = new javax.swing.JLabel();
        lblAccountBalance_S = new javax.swing.JLabel();
        lblAccountType_S = new javax.swing.JLabel();
        txtBankName_S = new javax.swing.JTextField();
        txtRoutingNumber_S = new javax.swing.JTextField();
        txtAccountNumber_S = new javax.swing.JTextField();
        lblFinalSavingsTitle = new javax.swing.JLabel();
        txtRoutingNumber_C = new javax.swing.JTextField();
        txtBankName_C = new javax.swing.JTextField();
        txtAccountNumber_C = new javax.swing.JTextField();
        txtAccountBalance_C = new javax.swing.JTextField();
        txtAccountType_C = new javax.swing.JTextField();
        lblBankName_C = new javax.swing.JLabel();
        lblRoutingNumber_C = new javax.swing.JLabel();
        lblAccountNumber_C = new javax.swing.JLabel();
        lblAccountBalance_C = new javax.swing.JLabel();
        lblAccountType_C = new javax.swing.JLabel();
        lblFinalCheckingTitle = new javax.swing.JLabel();
        lblIssuedDate = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        txtIssuedDate = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        lblLicenseNumber = new javax.swing.JLabel();
        lblFinalLicenseTitle = new javax.swing.JLabel();
        lblAlergy2 = new javax.swing.JLabel();
        lblAlergy3 = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtAlergy1 = new javax.swing.JTextField();
        txtAlergy2 = new javax.swing.JTextField();
        txtAlergy3 = new javax.swing.JTextField();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblAlergy1 = new javax.swing.JLabel();
        lblFinalMedicalTitle = new javax.swing.JLabel();
        lblFinalBankTitle = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        lblDisplayPicture = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("FirstName:");

        lblAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age:");

        lblLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("LastName:");

        txtDateOfBirth.setBackground(new java.awt.Color(204, 204, 204));
        txtDateOfBirth.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDateOfBirth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFirstName.setBackground(new java.awt.Color(204, 204, 204));
        txtFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHeight.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(255, 255, 255));
        lblHeight.setText("Height:");

        txtAge.setBackground(new java.awt.Color(204, 204, 204));
        txtAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblWeight.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(255, 255, 255));
        lblWeight.setText("Weight:");

        txtHeight.setBackground(new java.awt.Color(204, 204, 204));
        txtHeight.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtHeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        lblSSN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(255, 255, 255));
        lblSSN.setText("SSN:");

        lblPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setText("PhoneNumber:");

        txtWeight.setBackground(new java.awt.Color(204, 204, 204));
        txtWeight.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtLastName.setBackground(new java.awt.Color(204, 204, 204));
        txtLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSSN.setBackground(new java.awt.Color(204, 204, 204));
        txtSSN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSSN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDateOfBirth.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDateOfBirth.setForeground(new java.awt.Color(255, 255, 255));
        lblDateOfBirth.setText("Date of Birth:");

        txtPhoneNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblFinalPersonTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblFinalPersonTitle.setText("Person Information");

        txtState.setBackground(new java.awt.Color(204, 204, 204));
        txtState.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtState.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtZipCode.setBackground(new java.awt.Color(204, 204, 204));
        txtZipCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtZipCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        lblStreetAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblStreetAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStreetAddress.setText("Street Address:");

        lblCity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblState.setForeground(new java.awt.Color(255, 255, 255));
        lblState.setText("State:");

        lblZipCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblZipCode.setForeground(new java.awt.Color(255, 255, 255));
        lblZipCode.setText("Zip Code:");

        txtStreetAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtStreetAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtStreetAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressActionPerformed(evt);
            }
        });

        txtCity.setBackground(new java.awt.Color(204, 204, 204));
        txtCity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFinalAddressTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblFinalAddressTitle.setText("Address Information");

        txtAccountBalance_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountBalance_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAccountBalance_S.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAccountType_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountType_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAccountType_S.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBankName_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblBankName_S.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName_S.setText("Bank Name:");

        lblRoutingNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblRoutingNumber_S.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNumber_S.setText("Bank Routing Number:");

        lblAccountNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAccountNumber_S.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountNumber_S.setText("Bank Account Number:");

        lblAccountBalance_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAccountBalance_S.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountBalance_S.setText("Account Balance:");

        lblAccountType_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAccountType_S.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountType_S.setText("Account Type:");

        txtBankName_S.setBackground(new java.awt.Color(204, 204, 204));
        txtBankName_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtBankName_S.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBankName_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankName_SActionPerformed(evt);
            }
        });

        txtRoutingNumber_S.setBackground(new java.awt.Color(204, 204, 204));
        txtRoutingNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtRoutingNumber_S.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAccountNumber_S.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountNumber_S.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAccountNumber_S.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAccountNumber_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNumber_SActionPerformed(evt);
            }
        });

        lblFinalSavingsTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblFinalSavingsTitle.setText("Savings Account Information");

        txtRoutingNumber_C.setBackground(new java.awt.Color(204, 204, 204));
        txtRoutingNumber_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtRoutingNumber_C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtBankName_C.setBackground(new java.awt.Color(204, 204, 204));
        txtBankName_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtBankName_C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAccountNumber_C.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountNumber_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAccountNumber_C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAccountBalance_C.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountBalance_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAccountBalance_C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAccountType_C.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountType_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAccountType_C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBankName_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblBankName_C.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName_C.setText("Bank Name:");

        lblRoutingNumber_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblRoutingNumber_C.setForeground(new java.awt.Color(255, 255, 255));
        lblRoutingNumber_C.setText("Bank Routing Number:");

        lblAccountNumber_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAccountNumber_C.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountNumber_C.setText("Bank Account Number:");

        lblAccountBalance_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAccountBalance_C.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountBalance_C.setText("Account Balance:");

        lblAccountType_C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAccountType_C.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountType_C.setText("Account Type:");

        lblFinalCheckingTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblFinalCheckingTitle.setText("Checkings Account Information");

        lblIssuedDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblIssuedDate.setForeground(new java.awt.Color(255, 255, 255));
        lblIssuedDate.setText("Issued Date:");

        lblExpirationDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblExpirationDate.setForeground(new java.awt.Color(255, 255, 255));
        lblExpirationDate.setText("Date of Expiration:");

        lblBloodType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblBloodType.setForeground(new java.awt.Color(255, 255, 255));
        lblBloodType.setText("Blood Type:");

        txtLicenseNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtLicenseNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtLicenseNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtIssuedDate.setBackground(new java.awt.Color(204, 204, 204));
        txtIssuedDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtIssuedDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtExpirationDate.setBackground(new java.awt.Color(204, 204, 204));
        txtExpirationDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtExpirationDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtBloodType.setBackground(new java.awt.Color(204, 204, 204));
        txtBloodType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtBloodType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLicenseNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblLicenseNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblLicenseNumber.setText("License Number:");

        lblFinalLicenseTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblFinalLicenseTitle.setText("Driver's License Information");

        lblAlergy2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAlergy2.setForeground(new java.awt.Color(255, 255, 255));
        lblAlergy2.setText("Alergy2:");

        lblAlergy3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAlergy3.setForeground(new java.awt.Color(255, 255, 255));
        lblAlergy3.setText("Alergy3:");

        txtMedicalRecordNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtMedicalRecordNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMedicalRecordNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });

        txtAlergy1.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAlergy1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAlergy2.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAlergy2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAlergy3.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAlergy3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMedicalRecordNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMedicalRecordNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicalRecordNumber.setText("Medical Record Number:");

        lblAlergy1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAlergy1.setForeground(new java.awt.Color(255, 255, 255));
        lblAlergy1.setText("Alergy1:");

        lblFinalMedicalTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblFinalMedicalTitle.setText("Medical Record Information");

        lblFinalBankTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblFinalBankTitle.setText("Bank Details");

        lblPicture.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPicture.setForeground(new java.awt.Color(255, 255, 255));
        lblPicture.setText("License Picture:");

        lblDisplayPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBankName_S)
                                    .addComponent(lblRoutingNumber_S)
                                    .addComponent(lblAccountNumber_S)
                                    .addComponent(lblAccountBalance_S))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAccountNumber_S, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccountBalance_S, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRoutingNumber_S, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBankName_S, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lblAccountType_S)
                                .addGap(27, 27, 27)
                                .addComponent(txtAccountType_S, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblHeight)
                                                .addComponent(lblLastName)
                                                .addComponent(lblPhoneNumber)
                                                .addComponent(lblFirstName)
                                                .addComponent(lblDateOfBirth)
                                                .addComponent(lblAge))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblWeight)
                                                .addComponent(lblSSN))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(lblFinalPersonTitle)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAccountType_C)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtAccountType_C, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29))
                                        .addComponent(lblFinalCheckingTitle)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(lblFinalLicenseTitle)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblExpirationDate)
                                            .addComponent(lblIssuedDate)
                                            .addComponent(lblLicenseNumber)
                                            .addComponent(lblBloodType)
                                            .addComponent(lblPicture))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtBloodType)
                                                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                                    .addComponent(txtIssuedDate))
                                                .addGap(123, 123, 123))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblDisplayPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(70, 70, 70))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBankName_C)
                                    .addComponent(lblRoutingNumber_C)
                                    .addComponent(lblAccountNumber_C)
                                    .addComponent(lblAccountBalance_C))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRoutingNumber_C, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBankName_C, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccountNumber_C, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccountBalance_C, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(lblFinalAddressTitle))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblZipCode)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblCity)
                                                .addComponent(lblStreetAddress)
                                                .addComponent(lblState))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCity)
                                                .addComponent(txtZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                                .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblFinalSavingsTitle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAlergy1)
                                .addComponent(lblMedicalRecordNumber)
                                .addComponent(lblAlergy2)
                                .addComponent(lblAlergy3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(2, 2, 2))
                        .addComponent(lblFinalMedicalTitle, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(lblFinalBankTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAccountBalance_S, txtAccountNumber_S, txtAccountType_S, txtBankName_S, txtRoutingNumber_S});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAccountBalance_C, txtAccountNumber_C, txtAccountType_C, txtBankName_C, txtRoutingNumber_C});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAlergy1, txtAlergy2, txtAlergy3, txtMedicalRecordNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBloodType, txtExpirationDate, txtIssuedDate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCity, txtState, txtZipCode});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFinalPersonTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNumber)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateOfBirth)
                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFinalAddressTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreetAddress)
                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblState)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZipCode)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFinalBankTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinalSavingsTitle)
                    .addComponent(lblFinalCheckingTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankName_S)
                            .addComponent(txtBankName_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRoutingNumber_S)
                            .addComponent(txtRoutingNumber_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccountNumber_S)
                            .addComponent(txtAccountNumber_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccountBalance_S, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccountBalance_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankName_C)
                            .addComponent(txtBankName_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRoutingNumber_C)
                            .addComponent(txtRoutingNumber_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccountNumber_C)
                            .addComponent(txtAccountNumber_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccountBalance_C, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccountBalance_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAccountType_S)
                        .addComponent(txtAccountType_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAccountType_C)
                        .addComponent(txtAccountType_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFinalMedicalTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedicalRecordNumber)
                            .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlergy1)
                            .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlergy2)
                            .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFinalLicenseTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicenseNumber)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIssuedDate)
                            .addComponent(txtIssuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExpirationDate)
                            .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodType)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPicture)
                    .addComponent(lblDisplayPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAccountBalance_S, txtAccountNumber_S, txtAccountType_S, txtBankName_S, txtRoutingNumber_S});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAccountBalance_C, txtAccountNumber_C, txtAccountType_C, txtBankName_C, txtRoutingNumber_C});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAlergy1, txtAlergy2, txtAlergy3, txtMedicalRecordNumber});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBloodType, txtExpirationDate, txtIssuedDate, txtLicenseNumber});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCity, txtState, txtStreetAddress, txtZipCode});

    }// </editor-fold>//GEN-END:initComponents

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void txtStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressActionPerformed

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtAccountNumber_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNumber_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNumber_SActionPerformed

    private void txtBankName_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankName_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankName_SActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccountBalance_C;
    private javax.swing.JLabel lblAccountBalance_S;
    private javax.swing.JLabel lblAccountNumber_C;
    private javax.swing.JLabel lblAccountNumber_S;
    private javax.swing.JLabel lblAccountType_C;
    private javax.swing.JLabel lblAccountType_S;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAlergy1;
    private javax.swing.JLabel lblAlergy2;
    private javax.swing.JLabel lblAlergy3;
    private javax.swing.JLabel lblBankName_C;
    private javax.swing.JLabel lblBankName_S;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDisplayPicture;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblFinalAddressTitle;
    private javax.swing.JLabel lblFinalBankTitle;
    private javax.swing.JLabel lblFinalCheckingTitle;
    private javax.swing.JLabel lblFinalLicenseTitle;
    private javax.swing.JLabel lblFinalMedicalTitle;
    private javax.swing.JLabel lblFinalPersonTitle;
    private javax.swing.JLabel lblFinalSavingsTitle;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblIssuedDate;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblRoutingNumber_C;
    private javax.swing.JLabel lblRoutingNumber_S;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtAccountBalance_C;
    private javax.swing.JTextField txtAccountBalance_S;
    private javax.swing.JTextField txtAccountNumber_C;
    private javax.swing.JTextField txtAccountNumber_S;
    private javax.swing.JTextField txtAccountType_C;
    private javax.swing.JTextField txtAccountType_S;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAlergy1;
    private javax.swing.JTextField txtAlergy2;
    private javax.swing.JTextField txtAlergy3;
    private javax.swing.JTextField txtBankName_C;
    private javax.swing.JTextField txtBankName_S;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIssuedDate;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtRoutingNumber_C;
    private javax.swing.JTextField txtRoutingNumber_S;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtPhoneNumber.setText(person.getPhoneNumber());
        txtDateOfBirth.setText(person.getDateOfBirth());
        txtAge.setText(person.getAge());
        txtHeight.setText(person.getHeight());
        txtWeight.setText(person.getWeight());
        txtSSN.setText(person.getSsn());
        
        txtFirstName.setEditable(false);
        txtLastName.setEditable(false);
        txtPhoneNumber.setEditable(false);
        txtDateOfBirth.setEditable(false);
        txtAge.setEditable(false);
        txtHeight.setEditable(false);
        txtWeight.setEditable(false);
        txtSSN.setEditable(false);
    }

    private void displayaddress() {
        txtStreetAddress.setText(address.getStreetAddress());
        txtCity.setText(address.getCity());
        txtState.setText(address.getState());
        txtZipCode.setText(address.getZipCode());
        
        txtStreetAddress.setEditable(false);
        txtCity.setEditable(false);
        txtState.setEditable(false);
        txtZipCode.setEditable(false);
    }

    private void displayCheckingAccount() {
        txtBankName_C.setText(checkingAccount.getBankName_C());
        txtRoutingNumber_C.setText(checkingAccount.getBankRoutingNumber_C());
        txtAccountNumber_C.setText(checkingAccount.getBankAccountNumber_C());
        txtAccountBalance_C.setText(checkingAccount.getAccountBalance_C());
        txtAccountType_C.setText(checkingAccount.getAccountType_C());
        
        txtBankName_C.setEditable(false);
        txtRoutingNumber_C.setEditable(false);
        txtAccountNumber_C.setEditable(false);
        txtAccountBalance_C.setEditable(false);
        txtAccountType_C.setEditable(false);
    }

    private void displayBankDetails() {
         txtBankName_S.setText(bankdetails.getBankName());
         txtRoutingNumber_S.setText(bankdetails.getBankRoutingNumber());
         txtAccountNumber_S.setText(bankdetails.getBankAccountNumber());
         txtAccountBalance_S.setText(bankdetails.getAccountBalance());
         txtAccountType_S.setText(bankdetails.getAccountType());
         
         txtBankName_S.setEditable(false);
         txtRoutingNumber_S.setEditable(false);
         txtAccountNumber_S.setEditable(false);
         txtAccountBalance_S.setEditable(false);
         txtAccountType_S.setEditable(false);
    }

    private void displayLicenseInformation() {
        txtLicenseNumber.setText(licenseInformation.getLicenseNumber());
        txtIssuedDate.setText(licenseInformation.getIssuedDate());
        txtExpirationDate.setText(licenseInformation.getDateOfExpiration());
        txtBloodType.setText(licenseInformation.getBloodType());
        lblDisplayPicture.setIcon(licenseInformation.getPicture());
        
        txtLicenseNumber.setEditable(false);
        txtIssuedDate.setEditable(false);
        txtExpirationDate.setEditable(false);
        txtBloodType.setEditable(false);
    }

    private void displayMedicalRecord() {
        txtMedicalRecordNumber.setText(medicalRecord.getMedRecordNumber());
        txtAlergy1.setText(medicalRecord.getAlergy1());
        txtAlergy2.setText(medicalRecord.getAlergy2());
        txtAlergy3.setText(medicalRecord.getAlergy3());
        
        txtMedicalRecordNumber.setEditable(false);
        txtAlergy1.setEditable(false);
        txtAlergy2.setEditable(false);
        txtAlergy3.setEditable(false);
    }
}
