/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.ByteArrayOutputStream;
import javax.swing.JOptionPane;
import model.LicenseInformation;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author kalyanijohare
 */
public class LicenseInfoCreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LicenseInfoCreateJPanel
     */
    LicenseInformation licenseInformation;
    public LicenseInfoCreateJPanel(LicenseInformation licenseInformation) {
        initComponents();
        this.licenseInformation = licenseInformation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLicenseInfoTitle = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblIssuedDate = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        txtIssuedDate = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        btnSaveLicenseInfo = new javax.swing.JButton();
        btnUploadPicture = new javax.swing.JButton();
        lblImageDisplay = new javax.swing.JLabel();
        lblLicensePicture = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        lblLicenseInfoTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblLicenseInfoTitle.setText("Driver's License Information");

        lblLicenseNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLicenseNumber.setText("License Number:");

        lblIssuedDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIssuedDate.setText("Issued Date:");

        lblExpirationDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblExpirationDate.setText("Date of Expiration:");

        lblBloodType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBloodType.setText("Blood Type:");

        txtLicenseNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtLicenseNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtIssuedDate.setBackground(new java.awt.Color(204, 204, 204));
        txtIssuedDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIssuedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssuedDateActionPerformed(evt);
            }
        });

        txtExpirationDate.setBackground(new java.awt.Color(204, 204, 204));
        txtExpirationDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtExpirationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpirationDateActionPerformed(evt);
            }
        });

        txtBloodType.setBackground(new java.awt.Color(204, 204, 204));
        txtBloodType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodTypeActionPerformed(evt);
            }
        });

        btnSaveLicenseInfo.setBackground(new java.awt.Color(0, 102, 102));
        btnSaveLicenseInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSaveLicenseInfo.setText("Save");
        btnSaveLicenseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveLicenseInfoActionPerformed(evt);
            }
        });

        btnUploadPicture.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUploadPicture.setText("Upload Picture");
        btnUploadPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPictureActionPerformed(evt);
            }
        });

        lblLicensePicture.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLicensePicture.setText("License Picture:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblLicenseInfoTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblExpirationDate)
                            .addComponent(lblIssuedDate)
                            .addComponent(lblLicenseNumber)
                            .addComponent(lblBloodType)
                            .addComponent(lblLicensePicture))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIssuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUploadPicture)
                            .addComponent(lblImageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnSaveLicenseInfo)))
                .addContainerGap(495, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLicenseInfoTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicenseNumber)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIssuedDate)
                            .addComponent(txtIssuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblExpirationDate))
                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBloodType)
                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUploadPicture)
                    .addComponent(lblLicensePicture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSaveLicenseInfo)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveLicenseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveLicenseInfoActionPerformed
        // TODO add your handling code here:
        licenseInformation.setLicenseNumber(txtLicenseNumber.getText());
        licenseInformation.setIssuedDate(txtIssuedDate.getText());
        licenseInformation.setDateOfExpiration(txtExpirationDate.getText());
        licenseInformation.setBloodType(txtBloodType.getText());
        licenseInformation.setPicture(lblImageDisplay.getIcon());
        
        JOptionPane.showMessageDialog(this, "Driver's License Information Save Successfully");
    }//GEN-LAST:event_btnSaveLicenseInfoActionPerformed

    private void txtIssuedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssuedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssuedDateActionPerformed

    private void txtExpirationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpirationDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpirationDateActionPerformed

    private void txtBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodTypeActionPerformed

    private void btnUploadPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPictureActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        lblImageDisplay.setIcon(new ImageIcon(f.toString()));
        filename = f.getAbsolutePath();
        
    }//GEN-LAST:event_btnUploadPictureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveLicenseInfo;
    private javax.swing.JButton btnUploadPicture;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblImageDisplay;
    private javax.swing.JLabel lblIssuedDate;
    private javax.swing.JLabel lblLicenseInfoTitle;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblLicensePicture;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtIssuedDate;
    private javax.swing.JTextField txtLicenseNumber;
    // End of variables declaration//GEN-END:variables
    byte[] photo = null;
String filename = null;
}


