/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.LicenseInformation;

/**
 *
 * @author kalyanijohare
 */
public class LicenseInfoViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LicenseInfoViewJPanel
     */
    LicenseInformation licenseInformation;
    public LicenseInfoViewJPanel(LicenseInformation licenseInformation) {
        initComponents();
        this.licenseInformation = licenseInformation;
        displayLicenseInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIssuedDate = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        txtIssuedDate = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        lblLicenseInfoTitle = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblImageDisplay = new javax.swing.JLabel();
        lblLicensePicture = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        lblIssuedDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIssuedDate.setText("Issued Date:");

        lblExpirationDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblExpirationDate.setText("Date of Expiration:");

        lblBloodType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBloodType.setText("Blood Type:");

        txtLicenseNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtLicenseNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtIssuedDate.setBackground(new java.awt.Color(204, 204, 204));
        txtIssuedDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtExpirationDate.setBackground(new java.awt.Color(204, 204, 204));
        txtExpirationDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtBloodType.setBackground(new java.awt.Color(204, 204, 204));
        txtBloodType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblLicenseInfoTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblLicenseInfoTitle.setText("Driver's License Information");

        lblLicenseNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLicenseNumber.setText("License Number:");

        lblLicensePicture.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLicensePicture.setText("License Picture:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblLicenseInfoTitle)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBloodType)
                            .addComponent(lblExpirationDate)
                            .addComponent(lblIssuedDate)
                            .addComponent(lblLicenseNumber)
                            .addComponent(lblLicensePicture))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addContainerGap(707, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIssuedDate)
                                .addContainerGap(763, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtExpirationDate)
                                .addContainerGap(763, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBloodType)
                                .addContainerGap(763, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblLicenseInfoTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicenseNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIssuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIssuedDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExpirationDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloodType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicensePicture))
                .addContainerGap(341, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblImageDisplay;
    private javax.swing.JLabel lblIssuedDate;
    private javax.swing.JLabel lblLicenseInfoTitle;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblLicensePicture;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtIssuedDate;
    private javax.swing.JTextField txtLicenseNumber;
    // End of variables declaration//GEN-END:variables

    private void displayLicenseInformation() {
        txtLicenseNumber.setText(licenseInformation.getLicenseNumber());
        txtIssuedDate.setText(licenseInformation.getIssuedDate());
        txtExpirationDate.setText(licenseInformation.getDateOfExpiration());
        txtBloodType.setText(licenseInformation.getBloodType());
        lblImageDisplay.setIcon(licenseInformation.getPicture());
        
        txtLicenseNumber.setEditable(false);
        txtIssuedDate.setEditable(false);
        txtExpirationDate.setEditable(false);
        txtBloodType.setEditable(false);
    }
}
