/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.MedicalRecord;

/**
 *
 * @author kalyanijohare
 */
public class MedicalRecordViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalRecordViewJPanel
     */
    MedicalRecord medicalRecord;
    public MedicalRecordViewJPanel(MedicalRecord medicalRecord) {
        initComponents();
        this.medicalRecord = medicalRecord;
        displayMedicalRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblAlergy1 = new javax.swing.JLabel();
        lblAlergy2 = new javax.swing.JLabel();
        lblAlergy3 = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtAlergy1 = new javax.swing.JTextField();
        txtAlergy2 = new javax.swing.JTextField();
        txtAlergy3 = new javax.swing.JTextField();
        lblMedicalRecordTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        lblMedicalRecordNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMedicalRecordNumber.setText("Medical Record Number:");

        lblAlergy1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAlergy1.setText("Alergy1:");

        lblAlergy2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAlergy2.setText("Alergy2:");

        lblAlergy3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAlergy3.setText("Alergy3:");

        txtMedicalRecordNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtMedicalRecordNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });

        txtAlergy1.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAlergy2.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAlergy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergy2ActionPerformed(evt);
            }
        });

        txtAlergy3.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblMedicalRecordTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblMedicalRecordTitle.setText("Medical Record Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblMedicalRecordTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txtAlergy1)
                            .addComponent(txtAlergy2)
                            .addComponent(txtAlergy3))))
                .addContainerGap(654, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblAlergy1)
                        .addComponent(lblMedicalRecordNumber)
                        .addComponent(lblAlergy2)
                        .addComponent(lblAlergy3))
                    .addContainerGap(827, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblMedicalRecordTitle)
                .addGap(18, 18, 18)
                .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(lblMedicalRecordNumber)
                    .addGap(18, 18, 18)
                    .addComponent(lblAlergy1)
                    .addGap(22, 22, 22)
                    .addComponent(lblAlergy2)
                    .addGap(18, 18, 18)
                    .addComponent(lblAlergy3)
                    .addContainerGap(511, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtAlergy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergy2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAlergy1;
    private javax.swing.JLabel lblAlergy2;
    private javax.swing.JLabel lblAlergy3;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblMedicalRecordTitle;
    private javax.swing.JTextField txtAlergy1;
    private javax.swing.JTextField txtAlergy2;
    private javax.swing.JTextField txtAlergy3;
    private javax.swing.JTextField txtMedicalRecordNumber;
    // End of variables declaration//GEN-END:variables

    private void displayMedicalRecord() {
        txtMedicalRecordNumber.setText(medicalRecord.getMedRecordNumber());
        txtAlergy1.setText(medicalRecord.getAlergy1());
        txtAlergy2.setText(medicalRecord.getAlergy2());
        txtAlergy3.setText(medicalRecord.getAlergy3());
        
        txtMedicalRecordNumber.setEditable(false);
        txtAlergy1.setEditable(false);
        txtAlergy2.setEditable(false);
        txtAlergy3.setEditable(false);
    }
}
