/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.MedicalRecord;

/**
 *
 * @author kalyanijohare
 */
public class MedicalRecordCreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalRecordCreateJPanel
     */
    MedicalRecord medicalRecord;
    public MedicalRecordCreateJPanel(MedicalRecord medicalRecord) {
        initComponents();
        this.medicalRecord = medicalRecord;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedicalRecordTitle = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblAlergy1 = new javax.swing.JLabel();
        lblAlergy2 = new javax.swing.JLabel();
        lblAlergy3 = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtAlergy1 = new javax.swing.JTextField();
        txtAlergy2 = new javax.swing.JTextField();
        txtAlergy3 = new javax.swing.JTextField();
        btnSaveMedicalRecord = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        lblMedicalRecordTitle.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        lblMedicalRecordTitle.setText("Medical Record Information");

        lblMedicalRecordNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMedicalRecordNumber.setText("Medical Record Number:");

        lblAlergy1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAlergy1.setText("Alergy1:");

        lblAlergy2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAlergy2.setText("Alergy2:");

        lblAlergy3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAlergy3.setText("Alergy3:");

        txtMedicalRecordNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtMedicalRecordNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });

        txtAlergy1.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAlergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergy1ActionPerformed(evt);
            }
        });

        txtAlergy2.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtAlergy3.setBackground(new java.awt.Color(204, 204, 204));
        txtAlergy3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAlergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergy3ActionPerformed(evt);
            }
        });

        btnSaveMedicalRecord.setBackground(new java.awt.Color(0, 102, 102));
        btnSaveMedicalRecord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSaveMedicalRecord.setText("Save");
        btnSaveMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMedicalRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnSaveMedicalRecord))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedicalRecordTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAlergy1)
                                    .addComponent(lblMedicalRecordNumber)
                                    .addComponent(lblAlergy2)
                                    .addComponent(lblAlergy3))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(672, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMedicalRecordTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecordNumber)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy1)
                    .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy2)
                    .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy3)
                    .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveMedicalRecord)
                .addContainerGap(472, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void btnSaveMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMedicalRecordActionPerformed
        // TODO add your handling code here:
        medicalRecord.setMedRecordNumber(txtMedicalRecordNumber.getText());
        medicalRecord.setAlergy1(txtAlergy1.getText());
        medicalRecord.setAlergy2(txtAlergy2.getText());
        medicalRecord.setAlergy3(txtAlergy3.getText());
        
        JOptionPane.showMessageDialog(this, "Medical Record Saved Successfully");
    }//GEN-LAST:event_btnSaveMedicalRecordActionPerformed

    private void txtAlergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergy1ActionPerformed

    private void txtAlergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergy3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveMedicalRecord;
    private javax.swing.JLabel lblAlergy1;
    private javax.swing.JLabel lblAlergy2;
    private javax.swing.JLabel lblAlergy3;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblMedicalRecordTitle;
    private javax.swing.JTextField txtAlergy1;
    private javax.swing.JTextField txtAlergy2;
    private javax.swing.JTextField txtAlergy3;
    private javax.swing.JTextField txtMedicalRecordNumber;
    // End of variables declaration//GEN-END:variables
}
