/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Address;
import model.BankDetails;
import model.BankDetails_CheckingAcc;
import model.LicenseInformation;
import model.MedicalRecord;
import model.Person;

/**
 *
 * @author kalyanijohare
 */
public class PersonJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PersonJFrame
     */
    
    Person person;
    Address address;
    BankDetails bankdetails;
    BankDetails_CheckingAcc checkingAccount;
    LicenseInformation licenseInformation;
    MedicalRecord medicalRecord;
    public PersonJFrame() {
        initComponents();
        
        person = new Person();
        address = new Address();
        bankdetails = new BankDetails();
        checkingAccount = new BankDetails_CheckingAcc();
        licenseInformation = new LicenseInformation();
        medicalRecord = new MedicalRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanePerson = new javax.swing.JSplitPane();
        controlPanePerson = new javax.swing.JPanel();
        btnCreatePerson = new javax.swing.JButton();
        btnViewPerson = new javax.swing.JButton();
        btnCreateAddress = new javax.swing.JButton();
        btnViewAddress = new javax.swing.JButton();
        btnCreateSavingsAccountInformation = new javax.swing.JButton();
        btnViewSavingsAccountInformation = new javax.swing.JButton();
        btnCreateCheckingAccountInformation = new javax.swing.JButton();
        btnViewCheckingAccountInformation = new javax.swing.JButton();
        btnCreateDriverLicenseInfrormation = new javax.swing.JButton();
        btnViewDriverLicenseInformation = new javax.swing.JButton();
        btnCreateMedicalRecord = new javax.swing.JButton();
        btnViewMedicalRecord = new javax.swing.JButton();
        btnFinalView = new javax.swing.JButton();
        workAreaPerson = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanePerson.setBackground(new java.awt.Color(0, 102, 102));

        btnCreatePerson.setBackground(new java.awt.Color(204, 204, 204));
        btnCreatePerson.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnCreatePerson.setForeground(new java.awt.Color(0, 102, 102));
        btnCreatePerson.setText("CREATE PERSON INFORMATION");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnViewPerson.setBackground(new java.awt.Color(204, 204, 204));
        btnViewPerson.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnViewPerson.setForeground(new java.awt.Color(0, 102, 102));
        btnViewPerson.setText("VIEW PERSON INFORMATION");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnCreateAddress.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateAddress.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnCreateAddress.setForeground(new java.awt.Color(0, 102, 102));
        btnCreateAddress.setText("CREATE ADDRESS INFORMATION");
        btnCreateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddressActionPerformed(evt);
            }
        });

        btnViewAddress.setBackground(new java.awt.Color(204, 204, 204));
        btnViewAddress.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnViewAddress.setForeground(new java.awt.Color(0, 102, 102));
        btnViewAddress.setText("VIEW ADDRESS INFORMATION");
        btnViewAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddressActionPerformed(evt);
            }
        });

        btnCreateSavingsAccountInformation.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateSavingsAccountInformation.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnCreateSavingsAccountInformation.setForeground(new java.awt.Color(0, 102, 102));
        btnCreateSavingsAccountInformation.setText("CREATE SAVINGS ACCOUNT INFORMATION");
        btnCreateSavingsAccountInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSavingsAccountInformationActionPerformed(evt);
            }
        });

        btnViewSavingsAccountInformation.setBackground(new java.awt.Color(204, 204, 204));
        btnViewSavingsAccountInformation.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnViewSavingsAccountInformation.setForeground(new java.awt.Color(0, 102, 102));
        btnViewSavingsAccountInformation.setText("VIEW SAVINGS ACCOUNT INFORMATION");
        btnViewSavingsAccountInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSavingsAccountInformationActionPerformed(evt);
            }
        });

        btnCreateCheckingAccountInformation.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateCheckingAccountInformation.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnCreateCheckingAccountInformation.setForeground(new java.awt.Color(0, 102, 102));
        btnCreateCheckingAccountInformation.setText("CREATE CHECKINGS ACCOUNT INFORMATION");
        btnCreateCheckingAccountInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCheckingAccountInformationActionPerformed(evt);
            }
        });

        btnViewCheckingAccountInformation.setBackground(new java.awt.Color(204, 204, 204));
        btnViewCheckingAccountInformation.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnViewCheckingAccountInformation.setForeground(new java.awt.Color(0, 102, 102));
        btnViewCheckingAccountInformation.setText("VIEW CHECKINGS ACCOUNT INFORMATION");
        btnViewCheckingAccountInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCheckingAccountInformationActionPerformed(evt);
            }
        });

        btnCreateDriverLicenseInfrormation.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateDriverLicenseInfrormation.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnCreateDriverLicenseInfrormation.setForeground(new java.awt.Color(0, 102, 102));
        btnCreateDriverLicenseInfrormation.setText("CREATE DRIVER'S LICENSE INFORMATION");
        btnCreateDriverLicenseInfrormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDriverLicenseInfrormationActionPerformed(evt);
            }
        });

        btnViewDriverLicenseInformation.setBackground(new java.awt.Color(204, 204, 204));
        btnViewDriverLicenseInformation.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnViewDriverLicenseInformation.setForeground(new java.awt.Color(0, 102, 102));
        btnViewDriverLicenseInformation.setText("VIEW DRIVER'S LICENSE INFORMATION");
        btnViewDriverLicenseInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDriverLicenseInformationActionPerformed(evt);
            }
        });

        btnCreateMedicalRecord.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateMedicalRecord.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnCreateMedicalRecord.setForeground(new java.awt.Color(0, 102, 102));
        btnCreateMedicalRecord.setText("CREATE MEDICAL RECORD INFORMATION");
        btnCreateMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedicalRecordActionPerformed(evt);
            }
        });

        btnViewMedicalRecord.setBackground(new java.awt.Color(204, 204, 204));
        btnViewMedicalRecord.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnViewMedicalRecord.setForeground(new java.awt.Color(0, 102, 102));
        btnViewMedicalRecord.setText("VIEW MEDICAL RECORD INFORMATION");
        btnViewMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedicalRecordActionPerformed(evt);
            }
        });

        btnFinalView.setBackground(new java.awt.Color(204, 204, 204));
        btnFinalView.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnFinalView.setText("FINAL VIEW");
        btnFinalView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanePersonLayout = new javax.swing.GroupLayout(controlPanePerson);
        controlPanePerson.setLayout(controlPanePersonLayout);
        controlPanePersonLayout.setHorizontalGroup(
            controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanePersonLayout.createSequentialGroup()
                .addGroup(controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanePersonLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateCheckingAccountInformation)
                            .addComponent(btnViewCheckingAccountInformation)))
                    .addGroup(controlPanePersonLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnFinalView)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(controlPanePersonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanePersonLayout.createSequentialGroup()
                                .addGroup(controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnViewPerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanePersonLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViewAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreateAddress, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(controlPanePersonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewSavingsAccountInformation)
                            .addComponent(btnCreateSavingsAccountInformation, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanePersonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateDriverLicenseInfrormation, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewDriverLicenseInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(controlPanePersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewMedicalRecord)
                    .addComponent(btnCreateMedicalRecord))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlPanePersonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateAddress, btnCreateCheckingAccountInformation, btnCreateDriverLicenseInfrormation, btnCreateMedicalRecord, btnCreatePerson, btnCreateSavingsAccountInformation, btnViewAddress, btnViewCheckingAccountInformation, btnViewDriverLicenseInformation, btnViewMedicalRecord, btnViewPerson, btnViewSavingsAccountInformation});

        controlPanePersonLayout.setVerticalGroup(
            controlPanePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanePersonLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewPerson)
                .addGap(32, 32, 32)
                .addComponent(btnCreateAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAddress)
                .addGap(32, 32, 32)
                .addComponent(btnCreateSavingsAccountInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewSavingsAccountInformation)
                .addGap(32, 32, 32)
                .addComponent(btnCreateCheckingAccountInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewCheckingAccountInformation)
                .addGap(32, 32, 32)
                .addComponent(btnCreateDriverLicenseInfrormation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDriverLicenseInformation)
                .addGap(32, 32, 32)
                .addComponent(btnCreateMedicalRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewMedicalRecord)
                .addGap(18, 18, 18)
                .addComponent(btnFinalView, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        controlPanePersonLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreateAddress, btnCreateCheckingAccountInformation, btnCreateDriverLicenseInfrormation, btnCreateMedicalRecord, btnCreatePerson, btnCreateSavingsAccountInformation, btnViewAddress, btnViewCheckingAccountInformation, btnViewDriverLicenseInformation, btnViewMedicalRecord, btnViewPerson, btnViewSavingsAccountInformation});

        SplitPanePerson.setLeftComponent(controlPanePerson);

        workAreaPerson.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout workAreaPersonLayout = new javax.swing.GroupLayout(workAreaPerson);
        workAreaPerson.setLayout(workAreaPersonLayout);
        workAreaPersonLayout.setHorizontalGroup(
            workAreaPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1017, Short.MAX_VALUE)
        );
        workAreaPersonLayout.setVerticalGroup(
            workAreaPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );

        SplitPanePerson.setRightComponent(workAreaPerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SplitPanePerson))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanePerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        PersonCreateJPanel personCreateJPanel = new PersonCreateJPanel(person);
        SplitPanePerson.setRightComponent(personCreateJPanel);
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        // TODO add your handling code here:
        PersonViewJPanel personViewJPanel = new PersonViewJPanel(person);
        SplitPanePerson.setRightComponent(personViewJPanel);
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnCreateMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedicalRecordActionPerformed
        // TODO add your handling code here:
        MedicalRecordCreateJPanel medicalRecordCreateJPanel = new MedicalRecordCreateJPanel(medicalRecord);
        SplitPanePerson.setRightComponent(medicalRecordCreateJPanel);
    }//GEN-LAST:event_btnCreateMedicalRecordActionPerformed

    private void btnViewCheckingAccountInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCheckingAccountInformationActionPerformed
        // TODO add your handling code here:
        CheckingAccViewJPanel checkingAccViewJPanel = new CheckingAccViewJPanel(checkingAccount);
        SplitPanePerson.setRightComponent(checkingAccViewJPanel);
    }//GEN-LAST:event_btnViewCheckingAccountInformationActionPerformed

    private void btnCreateSavingsAccountInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSavingsAccountInformationActionPerformed
        // TODO add your handling code here:
        BankDetailsCreateJPanel bankDetailsCreateJPanel = new BankDetailsCreateJPanel(bankdetails);
        SplitPanePerson.setRightComponent(bankDetailsCreateJPanel);
    }//GEN-LAST:event_btnCreateSavingsAccountInformationActionPerformed

    private void btnCreateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddressActionPerformed
        // TODO add your handling code here:
        AddressCreateJPanel addressCreateJPanel = new AddressCreateJPanel(address);
        SplitPanePerson.setRightComponent(addressCreateJPanel);
    }//GEN-LAST:event_btnCreateAddressActionPerformed

    private void btnViewDriverLicenseInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDriverLicenseInformationActionPerformed
        // TODO add your handling code here:
        LicenseInfoViewJPanel licenseInfoViewJPanel = new LicenseInfoViewJPanel(licenseInformation);
        SplitPanePerson.setRightComponent(licenseInfoViewJPanel);
    }//GEN-LAST:event_btnViewDriverLicenseInformationActionPerformed

    private void btnViewMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedicalRecordActionPerformed
        // TODO add your handling code here:
        MedicalRecordViewJPanel medicalRecordViewJPanel = new MedicalRecordViewJPanel(medicalRecord);
        SplitPanePerson.setRightComponent(medicalRecordViewJPanel);
    }//GEN-LAST:event_btnViewMedicalRecordActionPerformed

    private void btnCreateCheckingAccountInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCheckingAccountInformationActionPerformed
        // TODO add your handling code here:
        CheckingAccCreateJPanel checkingAccCreateJPanel = new CheckingAccCreateJPanel(checkingAccount);
        SplitPanePerson.setRightComponent(checkingAccCreateJPanel);
    }//GEN-LAST:event_btnCreateCheckingAccountInformationActionPerformed

    private void btnViewAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddressActionPerformed
        // TODO add your handling code here:
        AddressViewJPanel addressViewJPanel = new AddressViewJPanel(address);
        SplitPanePerson.setRightComponent(addressViewJPanel);
    }//GEN-LAST:event_btnViewAddressActionPerformed

    private void btnViewSavingsAccountInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSavingsAccountInformationActionPerformed
        // TODO add your handling code here:
        BankDetailsViewJPanel bankDetailsViewJPanel = new BankDetailsViewJPanel(bankdetails);
        SplitPanePerson.setRightComponent(bankDetailsViewJPanel);
    }//GEN-LAST:event_btnViewSavingsAccountInformationActionPerformed

    private void btnCreateDriverLicenseInfrormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDriverLicenseInfrormationActionPerformed
        // TODO add your handling code here:
        LicenseInfoCreateJPanel licenseInfoCreateJPanel = new LicenseInfoCreateJPanel(licenseInformation);
        SplitPanePerson.setRightComponent(licenseInfoCreateJPanel);
    }//GEN-LAST:event_btnCreateDriverLicenseInfrormationActionPerformed

    private void btnFinalViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalViewActionPerformed
        // TODO add your handling code here:
        FinalViewJPanel finalViewJPanel = new FinalViewJPanel(person, address, bankdetails, checkingAccount, licenseInformation, medicalRecord);
        SplitPanePerson.setRightComponent((finalViewJPanel));
    }//GEN-LAST:event_btnFinalViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPanePerson;
    private javax.swing.JButton btnCreateAddress;
    private javax.swing.JButton btnCreateCheckingAccountInformation;
    private javax.swing.JButton btnCreateDriverLicenseInfrormation;
    private javax.swing.JButton btnCreateMedicalRecord;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnCreateSavingsAccountInformation;
    private javax.swing.JButton btnFinalView;
    private javax.swing.JButton btnViewAddress;
    private javax.swing.JButton btnViewCheckingAccountInformation;
    private javax.swing.JButton btnViewDriverLicenseInformation;
    private javax.swing.JButton btnViewMedicalRecord;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JButton btnViewSavingsAccountInformation;
    private javax.swing.JPanel controlPanePerson;
    private javax.swing.JPanel workAreaPerson;
    // End of variables declaration//GEN-END:variables
}
