

package userinterface.RestaurantAdminRole;


import Business.Restaurant.Restaurant;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private Restaurant restaurant;
    private JPanel activePanel;

    public Restaurant getRestaurant() {
        return restaurant;
    }

    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(Restaurant restaurant) {
        initComponents();
        this.restaurant = restaurant;
      
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(692, 303));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Manager Dashboard");

        MenuButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        MenuButton.setText("Manage Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });

        orderButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        orderButton.setText("Manage Orders");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(orderButton)
                .addGap(18, 18, 18)
                .addComponent(MenuButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        if(activePanel!=null) remove(activePanel);
        revalidate();
        repaint();
        activePanel = new MenuPanel(restaurant);
        activePanel.setBounds(200, 10, 273, 196);
        activePanel.setSize(430, 330);
        this.add(activePanel);
        revalidate();
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        if(activePanel!=null) remove(activePanel);
        revalidate();
        repaint();
        activePanel = new OrderPanel(restaurant);
        activePanel.setBounds(200, 10, 273, 196);
        activePanel.setSize(400, 300);
        this.add(activePanel);
        revalidate();
    }//GEN-LAST:event_orderButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderButton;
    // End of variables declaration//GEN-END:variables
    
}
